### ISSUE TITLE
Add Visual Studio alias to vscode

### ISSUE THREAD

**Issue by swade1987** [jammycakes/dotfiles#2]
Add the following to your `.zshrc` file

```
# Setup VS Code shortcut
alias vscode='code'

function code {
    if [[ $# = 0 ]]
    then
        open_command -a "Visual Studio Code"
    else
        local argPath="$1"
        [[ $1 = /* ]] && argPath="$1" || argPath="$PWD/${1#./}"
        open_command -a "Visual Studio Code" "$argPath"
    fi
}
```
This allows you to type `code .` in a directory and Visual Studio Code opens from there.

**Comment by jammycakes** [comment]
There isn't any need to do this. Visual Studio Code now installs the `code` command itself, in a platform-independent manner.
